import os

CENTRALIZER_SERVER = os.environ.get('CENTRALIZER_SERVER')
WSS_CENTRALIZER_SERVER = os.environ.get('WSS_CENTRALIZER_SERVER')
SERVER_TO_FORWARD = os.environ.get('SERVER_TO_FORWARD')
CHANEL_UUID = os.environ.get('CHANEL_UUID')
SOCKECTS_TIMEOUT = int(os.environ.get('SOCKECTS_TIMEOUT'))
